In [26]:
import pandas as pd
import numpy as np

In [27]:
data = pd.read_csv('./Data/test_data.csv', header=None)
label = pd.read_csv('./Data/test_label.csv', header=None)
data.columns = [f'a{i}' for i in data.columns]
label.columns = ['label']

In [28]:
# 填補缺失值
data_no_na = np.array(pd.DataFrame(data).fillna(pd.DataFrame(data).mean()))
data_no_na

array([[ 47. ,   1. , 163. , ...,   0.2,  11.5,  13.1],
       [ 57. ,   0. , 170. , ...,   2.3,  16. ,  38. ],
       [ 38. ,   1. , 172. , ...,   2. ,   9.4,  27. ],
       ...,
       [ 20. ,   0. , 186. , ...,   0.8,  19.5,  25.7],
       [ 26. ,   0. , 170. , ...,   1. ,  21. ,  28.4],
       [ 45. ,   0. , 169. , ...,  -0.9, -16.4, -25.4]])

In [29]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
data_scaled = scaler.fit_transform(data_no_na)

In [30]:
pd.DataFrame(data_scaled)

0         1         2         3         4         5         6     
0    0.138017  1.012739 -0.043020  0.914226 -0.525868 -0.477230 -0.192263  \
1    0.676454 -0.987421  0.530231  0.032679  0.323887  0.453438  1.747966   
2   -0.346576  1.012739  0.694017 -0.282159 -0.053782  0.234457  0.937124   
3    0.084173 -0.987421  1.185374  1.292032 -0.195408  0.070222  0.068364   
4   -0.077358 -0.987421  0.120766  0.914226  0.229470  0.654171 -0.945188   
..        ...       ...       ...       ...       ...       ...       ...   
153 -0.023514  1.012739 -0.534377 -0.345126 -0.337033 -0.112262  0.328992   
154 -0.454264 -0.987421  0.612124  0.662356 -0.242616  0.070222 -0.134346   
155 -1.315763 -0.987421  1.840518  0.032679 -0.006573 -0.531976  0.271075   
156 -0.992700 -0.987421  0.530231 -1.415576 -0.148199 -2.776530 -0.163305   
157  0.030330 -0.987421  0.448338  0.914226  0.465512  0.836655 -1.205816   

          7         8         9    ...       269       270       271   
0   -1.003980 -0.575577 -0.461553  ... -0.090264  0.504101 -0.818268  \
1   -0.295451 -0.094770  0.521169  ...  0.401517  0.504101  0.123709   
2   -0.676966  0.283007 -0.813850  ...  0.401517  0.504101 -1.184592   
3   -0.322702 -0.712951 -0.387386  ...  0.401517  0.504101  0.411535   
4   -0.595213  0.317350 -1.258856  ...  0.155627  0.504101 -1.734078   
..        ...       ...       ...  ...       ...       ...       ...   
153 -0.431706 -0.369517  0.298666  ...  0.155627  0.504101 -0.949098   
154 -0.104693 -0.094770  0.650963  ...  0.893298 -0.438479  0.019045   
155 -0.349953 -0.266487  0.447001  ... -0.090264 -0.909769  0.123709   
156 -0.622464  3.957747 -1.221773  ... -0.090264  0.504101 -0.425777   
157  1.203362  0.901187 -1.778030  ...  2.245695 -4.994283 -2.283565   

          272  273  274       275       276       277       278  
0    0.174524  0.0  0.0  0.014273 -0.671725 -0.485466 -0.864855  
1   -0.003838  0.0  0.0  0.264844  0.593192 -0.214194  0.347427  
2    0.317213  0.0  0.0  0.014273  0.412489 -0.612059 -0.188119  
3    0.317213  0.0  0.0 -0.486869  0.593192  0.581536  0.926791  
4   -0.824303  0.0  0.0 -0.236298 -1.274066 -1.709203 -2.145299  
..        ...  ...  ...       ...       ...       ...       ...  
153  0.031834  0.0  0.0  0.014273 -0.069384 -0.593974 -0.446155  
154  0.245869  0.0  0.0  0.264844  0.834128 -0.129798  0.736916  
155  0.317213  0.0  0.0  0.014273 -0.310320 -0.003205 -0.251411  
156  0.709610  0.0  0.0 -0.486869 -0.189852  0.087219 -0.119959  
157 -1.074010  0.0  0.0  2.018843 -1.334300 -2.167350 -2.739269  

[158 rows x 279 columns]

In [31]:
data_scaled.shape

(158, 279)

In [32]:
data_3d = np.reshape(data_scaled, (data_scaled.shape[0], data_scaled.shape[1], 1))

In [33]:
data_3d

array([[[ 0.13801705],
        [ 1.01273937],
        [-0.04301971],
        ...,
        [-0.67172496],
        [-0.48546572],
        [-0.86485542]],

       [[ 0.67645394],
        [-0.98742088],
        [ 0.53023085],
        ...,
        [ 0.59319185],
        [-0.21419401],
        [ 0.3474274 ]],

       [[-0.34657615],
        [ 1.01273937],
        [ 0.69401672],
        ...,
        [ 0.41248945],
        [-0.61205919],
        [-0.18811923]],

       ...,

       [[-1.31576255],
        [-0.98742088],
        [ 1.84051782],
        ...,
        [-0.31032016],
        [-0.0032049 ],
        [-0.2514111 ]],

       [[-0.99270042],
        [-0.98742088],
        [ 0.53023085],
        ...,
        [-0.18985189],
        [ 0.08721901],
        [-0.11995875]],

       [[ 0.03032967],
        [-0.98742088],
        [ 0.44833791],
        ...,
        [-1.33430043],
        [-2.16735036],
        [-2.73926862]]])

In [34]:
data_3d.shape

(158, 279, 1)

In [35]:
from tensorflow import keras

In [36]:
model = keras.models.load_model('./LSTM_Arrhythmia_2023-05-11_20-16-46.h5')
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 48)                9600      
                                                                 
 dropout (Dropout)           (None, 48)                0         
                                                                 
 batch_normalization (BatchN  (None, 48)               192       
 ormalization)                                                   
                                                                 
 dense (Dense)               (None, 36)                1764      
                                                                 
 dropout_1 (Dropout)         (None, 36)                0         
                                                                 
 batch_normalization_1 (Batc  (None, 36)               144       
 hNormalization)                                        

In [37]:
# 創建新模型，輸入是原始模型的輸入，輸出是中間層的輸出
predict_model = keras.Model(inputs=model.input, outputs=model.get_layer('batch_normalization_3').output)

In [38]:
predict = predict_model.predict(data_scaled)
predict

5/5 [==============================] - 0s 18ms/step


array([[-0.9755697 ,  1.6300032 , -1.7283384 , ...,  0.1728465 ,
        -0.68921345, -0.6649797 ],
       [ 0.36467016,  0.87370425, -1.7283384 , ...,  2.0957422 ,
        -1.0527941 ,  0.51595676],
       [-0.9755697 , -0.8123135 , -1.5781085 , ..., -0.24669746,
        -1.0527941 ,  1.3704822 ],
       ...,
       [-0.9755697 , -0.8123135 , -1.7283384 , ..., -0.3355167 ,
        -1.0527941 ,  1.4624007 ],
       [-0.9755697 , -0.8123135 , -1.1390722 , ..., -0.65603536,
        -1.0527941 ,  2.2849822 ],
       [ 3.1117444 ,  2.323918  , -1.0120733 , ..., -0.65603536,
         2.178484  , -0.6649797 ]], dtype=float32)

In [39]:
from sklearn.cluster import KMeans

# 設置聚類模型的參數，這裡設置為5群
n_clusters = 13
kmeans = KMeans(n_clusters=n_clusters, random_state=0)

# 進行聚類
predict_label = kmeans.fit_predict(predict)

# 打印每個樣本所屬的分類
eval_label = pd.concat([label, pd.DataFrame(predict_label, columns=['Predict'])], axis=1)
eval_label

C:\Users\eddie\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


label  Predict
0       13        3
1       10        6
2        6        0
3        1        1
4        2        8
..     ...      ...
153     10        1
154     10        5
155     10        0
156     10        0
157     13        2

[158 rows x 2 columns]

In [40]:
eval_label[eval_label['Predict'] == 0].value_counts()

label  Predict
1      0          12
10     0           8
6      0           2
13     0           2
Name: count, dtype: int64

In [41]:
eval_label[eval_label['Predict'] == 1].value_counts()

label  Predict
1      1          3
10     1          3
13     1          3
5      1          1
8      1          1
Name: count, dtype: int64

In [42]:
eval_label[eval_label['Predict'] == 2].value_counts()

label  Predict
10     2          3
3      2          2
12     2          2
2      2          1
9      2          1
13     2          1
Name: count, dtype: int64

In [43]:
eval_label[eval_label['Predict'] == 3].value_counts()

label  Predict
9      3          2
13     3          2
1      3          1
3      3          1
5      3          1
10     3          1
Name: count, dtype: int64

In [44]:
eval_label[eval_label['Predict'] == 4].value_counts()

label  Predict
10     4          3
1      4          2
4      4          1
Name: count, dtype: int64

In [45]:
eval_label[eval_label['Predict'] == 5].value_counts()

label  Predict
10     5          7
1      5          6
6      5          1
9      5          1
13     5          1
Name: count, dtype: int64

In [46]:
eval_label[eval_label['Predict'] == 6].value_counts()

label  Predict
10     6          7
1      6          2
13     6          1
Name: count, dtype: int64

In [48]:
eval_label[eval_label['Predict'] == 7].value_counts()

label  Predict
9      7          2
13     7          1
Name: count, dtype: int64

In [49]:
eval_label[eval_label['Predict'] == 8].value_counts()

label  Predict
2      8          2
9      8          2
13     8          2
1      8          1
10     8          1
11     8          1
12     8          1
Name: count, dtype: int64

In [50]:
eval_label[eval_label['Predict'] == 9].value_counts()

label  Predict
1      9          3
13     9          3
11     9          2
Name: count, dtype: int64

In [51]:
eval_label[eval_label['Predict'] == 10].value_counts()

label  Predict
1      10         4
13     10         2
2      10         1
10     10         1
11     10         1
Name: count, dtype: int64

In [52]:
eval_label[eval_label['Predict'] == 11].value_counts()

label  Predict
1      11         7
10     11         7
12     11         2
13     11         1
Name: count, dtype: int64

In [53]:
eval_label[eval_label['Predict'] == 12].value_counts()

label  Predict
1      12         9
10     12         9
2      12         3
13     12         3
5      12         1
9      12         1
Name: count, dtype: int64